apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: stop-crash-eventlistener
  namespace: devops
spec:
  serviceAccountName: pipeline-runner
  triggers:
    - triggerRef: stop-crash-trigger
